import { Art } from '../artworks/art';

export const ARTWORK:[Art[]] = [
  [
    { id: 1000000, 
      title: 'Cheerleader Cookie Bouquet', 
      category: 'Cookies', 
      summary: 'A bouquet of decorated cheerleader sugar cookies',
      coverImg: 'assets/images/cheer.jpg',
      desc: '',
      date: '2011',
      content: [
        {img:'assets/images/cheer.jpg', 
         desc: '<p>I made this bouqet for my daughter to take to her cheerleading squad\'s Christmas party</p>'}
      ],
    },
    { id: 1000001, 
      title: 'Iced Decorated Christmas Cookies', 
      category: 'Cookies', 
      summary: 'Christmas-theme sugar cookies iced with royal icing', 
      coverImg: 'assets/images/redWhiteChristmas.jpg',
      desc: '<p>I love making brightly colored cookies for Christmas!</p>',
      date: '2011',
      content: [
        {img:'assets/images/redWhiteChristmas.jpg', 
         desc: ''},
        {img: 'assets/images/blueWhiteChristmas.jpg', desc: "" },
        {img: 'assets/images/redChristmas.jpg', desc: "" },
        {img: 'assets/images/redWhiteChristmas.jpg', desc: "" },
        {img: 'assets/images/greenChristmas.jpg', desc: "" },
        {img: 'assets/images/christmaskids.jpg', desc: "" },
        {img: 'assets/images/redBlueGreenChristmas.jpg', desc: "" }
      ],
    },
    { id: 1000002, 
      title: 'Animal Ideas', 
      category: 'Cookies', 
      summary: 'Rough ideas for decorating animal cookies', 
      coverImg: 'assets/images/artwork/cookies/animals.jpg',
      desc: '<p>So these are not my best work.  Rather, they are cookies I made up and decorated quickly in order to get ideas for how to decorate these cutter shapes in the future.  I was also experimenting with different types of royal icing to see which had the best flavor and best consistency.</p>',
      date: '16 Oct 2012',
      content: [
        {img:'assets/images/artwork/cookies/animals.jpg', desc: ''},
        {img: 'assets/images/artwork/cookies/greencreatures.jpg', desc: "" },
        {img: 'assets/images/artwork/cookies/yellowbirds.jpg', desc: "" }
      ],
    },
    { id: 1000003, 
      title: 'Christmas Cookie Bouquets', 
      category: 'Cookies', 
      summary: 'Rough ideas for decorating animal cookies', 
      coverImg: 'assets/images/artwork/cookies/animals.jpg',
      desc: '<p>So these are not my best work.  Rather, they are cookies I made up and decorated quickly in order to get ideas for how to decorate these cutter shapes in the future.  I was also experimenting with different types of royal icing to see which had the best flavor and best consistency.</p>',
      date: '16 Oct 2012',
      content: [
        {img:'assets/images/artwork/cookies/animals.jpg', desc: ''},
        {img: 'assets/images/artwork/cookies/greencreatures.jpg', desc: "" },
        {img: 'assets/images/artwork/cookies/yellowbirds.jpg', desc: "" }
      ],
    }
  ],
  [
    { id: 2000000, 
      title: 'Apple Blossoms Cake', 
      category: 'Decorated Cakes', 
      summary: 'A simple but pretty layer cake',
      coverImg: 'assets/images/appleblossoms.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/appleblossoms.jpg', 
         desc: '<p>This cake design came from Wilton\'s gallery.</p>'}
      ]
    },
    { id: 2000001, 
      title: 'Baseball Team Cake', 
      category: 'Decorated Cakes', 
      summary: 'Star-covered cake for season\'s end celebration',
      coverImg: 'assets/images/artwork/cakes/Baseball_sides.jpg',
      desc: '',
      date: '5 Nov 2012',
      content: [
        {img:'assets/images/artwork/cakes/Baseball_sides.jpg', 
         desc: '<p>Large sheet cake I made for my son\'s baseball team.</p>'}
      ]
    },
    { id: 2000002, 
      title: 'Basket of Roses Cake', 
      category: 'Decorated Cakes', 
      summary: 'Sweet pink roses in a pink basket',
      coverImg: 'assets/images/artwork/cakes/basketofroses.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/basketofroses.jpg', 
         desc: '<p>Another Wilton cake design...</p>'}
      ]
    },
    { id: 2000003, 
      title: 'Bavarian Chapel Cake', 
      category: 'Decorated Cakes', 
      summary: 'A Bavaria-themed anniversary cake',
      coverImg: 'assets/images/artwork/cakes/bavarianChapel.jpg',
      desc: '',
      date: '5 Nov 2012',
      content: [
        {img:'assets/images/artwork/cakes/bavarianChapel.jpg', 
         desc: '<p>I made this cake for a friend\'s parents who were celebrating their 50th wedding anniversary. &nbsp;They were married in Bavaria so my friend wanted a cake that would remind them of their wedding.</p>'}
      ]
    },
    { id: 2000004, 
      title: 'Blossoms & Butterflies Cake', 
      category: 'Decorated Cakes', 
      summary: 'Brightly colored cake with royal icing flowers and butterflies',
      coverImg: 'assets/images/artwork/cakes/blossombutterflies.jpg',
      desc: '',
      date: '15 Oct 2012',
      content: [
        {img:'assets/images/artwork/cakes/blossombutterflies.jpg', 
         desc: '<p>Here is a tiered cake that I made for the annual auction at my kids\' school. &nbsp;I called it \'Butterflies and Blossoms\'. &nbsp;It is a white chocolate cake with raspberry filling, iced in buttercream. &nbsp;The flowers (roses, apple blossoms and individual petals) are made from royal icing and were heavily inspired by a cake called "Flower Tower" that I found in&nbsp;</span><a href="http://www.amazon.com/Wilton-902-1108-Tiered-Cakes/dp/B000FH0RRO/ref=sr_1_1?ie=UTF8&amp;qid=1350158477&amp;sr=8-1&amp;keywords=wilton+tiered+cakes+book" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; line-height: normal;">Wilton Tiered Cakes</a><span style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; line-height: normal;">. &nbsp;The butterfly wings were made by outlining the shapes then flooding the inside with liquid royal icing. &nbsp;The butterflies (patterned from Peggy Porchen\'s&nbsp;</span><a href="http://www.amazon.com/Pretty-Party-Cakes-Stylish-Occasions/dp/0307337073/ref=sr_1_1?s=books&amp;ie=UTF8&amp;qid=1350158587&amp;sr=1-1&amp;keywords=pretty+party+cakes" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; line-height: normal;">Pretty Party Cakes</a><span style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; line-height: normal;">&nbsp;book) were constructed after the wings were fully dried using stiff royal icing for their bodies. &nbsp;</span></p>'},
        {img:'assets/images/artwork/cakes/butterfliesblossoms.jpg', 
         desc: '<p>Here\'s another version of the cake made two years after the first. &nbsp;I added a fence to the top and the flower colors were darker. &nbsp;(I prefer the ligher colors.)</p>'}
      ]
    },
    { id: 2000005, 
      title: 'Chocolate Lace Cake', 
      category: 'Decorated Cakes', 
      summary: 'Chocolate through and through: cake, buttercream and candy scrolls',
      coverImg: 'assets/images/artwork/cakes/chocolatelace.jpg',
      desc: '',
      date: '5 Nov 2012',
      content: [
        {img:'assets/images/artwork/cakes/chocolatelace.jpg', 
         desc: '<p>This is a chocolate cake filled and iced with chocolate buttercream  The lace scrolls were piped from melted chocolate.  The pattern for the scrolls came from a Wilton book I have along with the cake inspiration.</p>'}
      ]
    },
    { id: 2000006, 
      title: 'Chocolate Malted Milk Ball Cake', 
      category: 'Decorated Cakes', 
      summary: 'Chocoate cake with a crunch!',
      coverImg: 'assets/images/artwork/cakes/maltedmilkballcake.jpg',
      desc: '',
      date: '5 Nov 2012',
      content: [
        {img:'assets/images/artwork/cakes/maltedmilkballcake.jpg', 
         desc: '<p>Malted milk balls and chocolate cake are each yummy on their own so they must be doubly good together, right?  Right!</p>'}
      ]
    },
    { id: 2000007, 
      title: 'Daisies and Mums Cake', 
      category: 'Decorated Cakes', 
      summary: 'Royal icing flowers on a basic white cake',
      coverImg: 'assets/images/artwork/cakes/DaisiesMumsBasket.jpg',
      desc: '',
      date: '5 Nov 2012',
      content: [
        {img:'assets/images/artwork/cakes/DaisiesMumsBasket.jpg', 
         desc: '<p>Made this cake to use up some practice daisies and chrysanthemums I piped in royal.</p>'}
      ]
    },
    { id: 2000008, 
      title: 'Dilbert and Dogbert Copier Fun Cake', 
      category: 'Decorated Cakes', 
      summary: 'Office celebration cake featuring Dilbert and Dogbert',
      coverImg: 'assets/images/artwork/cakes/dilbert2.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/dilbert2.jpg', 
         desc: '<p>My husband asked me to make this cake for a colleague who was moving on to a new job. &nbsp;He wanted it to look like the Dilbert and Dogbert cartoon where they are playing on the copier machine.</p>'}
      ]
    },
    { id: 2000009, 
      title: 'Hungry Caterpillar Cake', 
      category: 'Decorated Cakes', 
      summary: 'A very hungry caterpillar encircles a red apple',
      coverImg: 'assets/images/artwork/cakes/HungryCaterpillar.jpg',
      desc: '',
      date: '5 Nov 2012',
      content: [
        {img:'assets/images/artwork/cakes/HungryCaterpillar.jpg', 
         desc: '<p>I loved this cake! &nbsp;It was for my youngest son\'s birthday. &nbsp;The caterpillar is made of cupcakes that were dipped in green melted candy in lieu of paper baking cups. &nbsp;The apple was made from Wilton\'s ball mold. The caterpillar and apple sit on a buttercream-grass-topped cake base.</p>'}
      ]
    },
    { id: 20000010, 
      title: 'Penny Black Kitty Cake', 
      category: 'Decorated Cakes', 
      summary: 'A rubber-stamp inspired cake',
      coverImg: 'assets/images/artwork/cakes/kittycake.jpg',
      desc: '<p>My daughter wanted a kitty cake for her birthday so I borrowed the design for the cake from a Penny Black rubber stamp.&nbsp;.</p>',
      date: '5 Nov 2012',
      content: [
        {img:'assets/images/artwork/cakes/kittytop.jpg', 
         desc: ''},
         {img:'assets/images/artwork/cakes/kittycake.jpg', 
         desc: ''}
      ]
    },
    { id: 20000011, 
      title: 'Pikachu Cake', 
      category: 'Decorated Cakes', 
      summary: 'A birthday cake for Pika lovers',
      coverImg: 'assets/images/artwork/cakes/pikachu.jpg',
      desc: '',
      date: '5 Nov 2012',
      content: [
        {img:'assets/images/artwork/cakes/pikachu.jpg', 
         desc: '<p>A Pikachu birthday cake I made many years ago.</p>'}
      ]
    },
    { id: 20000012, 
      title: 'Pokemon Cake', 
      category: 'Decorated Cakes', 
      summary: 'A Pokemon daycare cake',
      coverImg: 'assets/images/artwork/cakes/pokemoncake.jpg',
      desc: '',
      date: '5 Nov 2012',
      content: [
        {img:'assets/images/artwork/cakes/pokemoncake.jpg', 
         desc: '<p>Another pokemon birthday theme. &nbsp;This time, the pokemon (made from marshmellow fondant) are in their habitat -- grass pokemon in the grass, water pokemon in the pond, etc. &nbsp;:)</p>'}
      ]
    },
    { id: 20000013, 
      title: 'Pokemon Cupcakes', 
      category: 'Decorated Cakes', 
      summary: 'A tower of starter Pokemon',
      coverImg: 'assets/images/artwork/cakes/pokemoncupcakes.jpg',
      desc: '',
      date: '5 Nov 2012',
      content: [
        {img:'assets/images/artwork/cakes/pokemoncupcakes.jpg', 
         desc: '<p>My sons loved pokemon so for several years, I made pokemon cakes. &nbsp;Here\'s one with cupcakes. &nbsp;The pokemon are made from marshmallow fondant.</p>'}
      ]
    },
    { id: 20000014, 
      title: 'Sitting Monkies Cake', 
      category: 'Decorated Cakes', 
      summary: 'A large monkey cake and mini, take-home monkey cakes',
      coverImg: 'assets/images/artwork/cakes/monkeys.jpg',
      desc: '',
      date: '6 Nov 2012',
      content: [
        {img:'assets/images/artwork/cakes/monkeys.jpg', 
         desc: '<p>The monkeys were made using the large and small bear forms by Wilton.</p>'}
      ]
    },
    { id: 20000015, 
      title: 'Sweatheart Cake', 
      category: 'Decorated Cakes', 
      summary: 'Fondant hearts, bows and flowers for a little girl\'s birthday',
      coverImg: 'assets/images/artwork/cakes/Melanie.jpg',
      desc: '',
      date: '5 Nov 2012',
      content: [
        {img:'assets/images/artwork/cakes/Melanie.jpg', 
         desc: '<p>I made this cake for the birthday of a friend\'s daughter. &nbsp;The heart-shaped cake is iced with off-white buttercream on top and pink buttercream on the sides. &nbsp;The white hearts along the top edge were cut from white fondant. &nbsp;The bows and flowers are also fondant.</p>'}
      ]
    },
    { id: 20000016, 
      title: 'Tiered Rose Wedding Cake', 
      category: 'Decorated Cakes', 
      summary: 'A just-for-practice white, multi-tier cake',
      coverImg: 'assets/images/artwork/cakes/AngelsSing.jpg',
      desc: '',
      date: '5 Nov 2012',
      content: [
        {img:'assets/images/artwork/cakes/AngelsSing.jpg', 
         desc: '<p>This was a practice wedding cake I made, inspired by a Wilton cake called Angels Sing.</p>'}
      ]
    },
    { id: 20000017, 
      title: 'Volleyball Cake', 
      category: 'Decorated Cakes', 
      summary: 'A volleyball-theme cake with cookie players and candy stars',
      coverImg: 'assets/images/artwork/cakes/vballcake.jpg',
      desc: '',
      date: '6 Nov 2012',
      content: [
        {img:'assets/images/artwork/cakes/vballcake.jpg', 
         desc: '<p>This cake was for my daughter\'s volleyball team. &nbsp;The volleyball was made from one half of Wilton\'s ball form. &nbsp;The stars are made from yellow candy melts. &nbsp;The volleyball players are sugar cookies cut with a gingerbread man cutter and iced in royal.</p>'}
      ]
    },
    { id: 20000018, 
      title: 'Wilton Course 1 Final Cake', 
      category: 'Decorated Cakes', 
      summary: 'Demonstrates buttercream icing smoothing and piping techniques',
      coverImg: 'assets/images/artwork/cakes/course1.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/course1.jpg', 
         desc: '<p>This was the final cake from the first Wilton cake decorating class. &nbsp;It was a fun class where we learned to make different consistencies of buttercream for icing, piping and roses.</p>'}
      ]
    },
    { id: 20000019, 
      title: 'Wilton Course 2 Final Cake', 
      category: 'Decorated Cakes', 
      summary: 'A cake that features beginning royal icing flowers and figures',
      coverImg: 'assets/images/artwork/cakes/Course2c.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/Course2c.jpg', 
         desc: '<p>If you took the second Wilton cake decorating class, you probably recognize this cake... it\'s from the final session of the class.</p>'}
      ]
    },
    { id: 20000020, 
      title: 'Wilton Course 3 Final Cake', 
      category: 'Decorated Cakes', 
      summary: 'The final project for the final cake decorating course',
      coverImg: 'assets/images/artwork/cakes/course3.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/course3.jpg', 
         desc: '<p>This was the final cake from the third Wilton cake decorating class. &nbsp;It was the first tiered cake I ever made and I had a little problem getting the columns in plumb! &nbsp;</p>'}
      ]
    },
    { id: 20000021, 
      title: 'Resting Dogs Cake', 
      category: 'Decorated Cakes', 
      summary: 'The final project for the final cake decorating course',
      coverImg: 'assets/images/artwork/cakes/dogcake.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/course3.jpg', 
         desc: '<p>This was the final cake from the third Wilton cake decorating class. &nbsp;It was the first tiered cake I ever made and I had a little problem getting the columns in plumb! &nbsp;</p>'}
      ]
    },
    { id: 20000021, 
      title: 'Fondant Car Cake', 
      category: 'Decorated Cakes', 
      summary: 'The final project for the final cake decorating course',
      coverImg: 'assets/images/artwork/cakes/fondantcar.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/course3.jpg', 
         desc: '<p>This was the final cake from the third Wilton cake decorating class. &nbsp;It was the first tiered cake I ever made and I had a little problem getting the columns in plumb! &nbsp;</p>'}
      ]
    },
    { id: 20000022, 
      title: 'Fondant Leaves Cake', 
      category: 'Decorated Cakes', 
      summary: 'The final project for the final cake decorating course',
      coverImg: 'assets/images/artwork/cakes/fondantleaves.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/course3.jpg', 
         desc: '<p>This was the final cake from the third Wilton cake decorating class. &nbsp;It was the first tiered cake I ever made and I had a little problem getting the columns in plumb! &nbsp;</p>'}
      ]
    },
    { id: 20000023, 
      title: 'Heavenly Treasures Cake', 
      category: 'Decorated Cakes', 
      summary: 'The final project for the final cake decorating course',
      coverImg: 'assets/images/artwork/cakes/FondantTreasureBox.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/course3.jpg', 
         desc: '<p>This was the final cake from the third Wilton cake decorating class. &nbsp;It was the first tiered cake I ever made and I had a little problem getting the columns in plumb! &nbsp;</p>'}
      ]
    },
    { id: 20000024, 
      title: 'Bunches of Blossoms Cake', 
      category: 'Decorated Cakes', 
      summary: 'The final project for the final cake decorating course',
      coverImg: 'assets/images/artwork/cakes/ForCarol.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/course3.jpg', 
         desc: '<p>This was the final cake from the third Wilton cake decorating class. &nbsp;It was the first tiered cake I ever made and I had a little problem getting the columns in plumb! &nbsp;</p>'}
      ]
    },
    { id: 20000025, 
      title: 'Guitar Cake', 
      category: 'Decorated Cakes', 
      summary: 'The final project for the final cake decorating course',
      coverImg: 'assets/images/artwork/cakes/guitar.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/course3.jpg', 
         desc: '<p>This was the final cake from the third Wilton cake decorating class. &nbsp;It was the first tiered cake I ever made and I had a little problem getting the columns in plumb! &nbsp;</p>'}
      ]
    },
    { id: 20000026, 
      title: 'Monogrammed Heart Cake', 
      category: 'Decorated Cakes', 
      summary: 'The final project for the final cake decorating course',
      coverImg: 'assets/images/artwork/cakes/Hheart.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/course3.jpg', 
         desc: '<p>This was the final cake from the third Wilton cake decorating class. &nbsp;It was the first tiered cake I ever made and I had a little problem getting the columns in plumb! &nbsp;</p>'}
      ]
    },
    { id: 20000027, 
      title: 'Hot Wheels Cake', 
      category: 'Decorated Cakes', 
      summary: 'The final project for the final cake decorating course',
      coverImg: 'assets/images/artwork/cakes/hotwheels.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/course3.jpg', 
         desc: '<p>This was the final cake from the third Wilton cake decorating class. &nbsp;It was the first tiered cake I ever made and I had a little problem getting the columns in plumb! &nbsp;</p>'}
      ]
    },
    { id: 20000028, 
      title: 'Royal Lace Extensions Cake', 
      category: 'Decorated Cakes', 
      summary: 'The final project for the final cake decorating course',
      coverImg: 'assets/images/artwork/cakes/LaceExtension.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/course3.jpg', 
         desc: '<p>This was the final cake from the third Wilton cake decorating class. &nbsp;It was the first tiered cake I ever made and I had a little problem getting the columns in plumb! &nbsp;</p>'}
      ]
    },
    { id: 20000029, 
      title: 'Sackboy Cake', 
      category: 'Decorated Cakes', 
      summary: 'The final project for the final cake decorating course',
      coverImg: 'assets/images/artwork/cakes/sackboy1.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/course3.jpg', 
         desc: '<p>This was the final cake from the third Wilton cake decorating class. &nbsp;It was the first tiered cake I ever made and I had a little problem getting the columns in plumb! &nbsp;</p>'}
      ]
    },
    { id: 20000030, 
      title: 'Snowflake Cake', 
      category: 'Decorated Cakes', 
      summary: 'The final project for the final cake decorating course',
      coverImg: 'assets/images/artwork/cakes/snowflakecake.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/course3.jpg', 
         desc: '<p>This was the final cake from the third Wilton cake decorating class. &nbsp;It was the first tiered cake I ever made and I had a little problem getting the columns in plumb! &nbsp;</p>'}
      ]
    },
    { id: 20000031, 
      title: 'Soccer Ball Cake', 
      category: 'Decorated Cakes', 
      summary: 'The final project for the final cake decorating course',
      coverImg: 'assets/images/artwork/cakes/soccerBall.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/course3.jpg', 
         desc: '<p>This was the final cake from the third Wilton cake decorating class. &nbsp;It was the first tiered cake I ever made and I had a little problem getting the columns in plumb! &nbsp;</p>'}
      ]
    },
    { id: 20000032, 
      title: 'SpongeBob SquarePants Cake', 
      category: 'Decorated Cakes', 
      summary: 'The final project for the final cake decorating course',
      coverImg: 'assets/images/artwork/cakes/spongebob.jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/course3.jpg', 
         desc: '<p>This was the final cake from the third Wilton cake decorating class. &nbsp;It was the first tiered cake I ever made and I had a little problem getting the columns in plumb! &nbsp;</p>'}
      ]
    },
    { id: 20000033, 
      title: 'Thomas the Tank Engine Cake', 
      category: 'Decorated Cakes', 
      summary: 'The final project for the final cake decorating course',
      coverImg: 'assets/images/artwork/cakes/thomas .jpg',
      desc: '',
      date: '18 Dec 2012',
      content: [
        {img:'assets/images/artwork/cakes/course3.jpg', 
         desc: '<p>This was the final cake from the third Wilton cake decorating class. &nbsp;It was the first tiered cake I ever made and I had a little problem getting the columns in plumb! &nbsp;</p>'}
      ]
    }
  ],
  [
    { id: 3000000, 
      title: 'Enjoy Simple Things Card', 
      category: 'Handmade Cards', 
      summary: 'Penny Black three-sheep stamp, divided', 
      coverImg: 'assets/images/sheep.jpg',
      desc: '',
      date: '2011',
      content: [
        {img:'assets/images/sheep.jpg',
         desc: '<p>The sheep came from a single Penny Black stamp that had all three lined up side-by-side.  I colored each one at a time with black pen and stamped it, completely cleaning the stamp between each.</p>'}
      ]
    }
  ],
  [
    { id: 4000000, 
      title: '"Rainbow Garden" Millefiori Candlesticks', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/candlesticks/candlesticks.jpg',
      desc: '',
      date: '2013',
      content: [
        {img:'assets/images/artwork/clay/candlesticks/candlesticks.jpg',
         desc: '<p>This year, the kids made canes again for the auction and we covered pillar candleholders and a candle snuffer with them.</p><p>The canes were different this year because they weren\'t surrounded with a background color.  Instead, transluscent clay was placed between petals/wings/etc. to help them hold their shapes while being reduced.  Then I cut out the transluscent separator pieces from the thin slices of the canes, which was very time consuming.  But I think it gives a nicer overlapping finish than if the transluscent is not removed.</p>'}
      ]
    },
    { id: 4000001, 
      title: 'Apple Blossom Cane', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/appleblossom/appblossm21.jpg',
      desc: '<p>These instructions are for the auction project.</p><p>Materials:&nbsp;</p><p style="margin-bottom: 0.0001pt;"><span style="font-size: 8.5pt; font-family: Verdana, sans-serif;">1 - 1" ball for inner petals<br /> 1 - 1/2" x 2" outer vein strip<br /> 1 - 1/2" x 1" inner vein strip<br /> 1 - 9" x 1" flat Skinner blend for outer petals<br /> 1 - 4" x 1" flat outline strip<br /> 1 - 3/8" ball for center</span></p>',
      date: '19 Jan 2013',
      content: [
        {img:"assets/images/artwork/clay/appleblossom/appblossm1.jpg",
         desc: '<p>Roll the inner petal ball into a 1.75-inch long round log.</p>'},
        {img:"assets/images/artwork/clay/appleblossom/appblossm2.jpg",
         desc: '<p>Shape the log into a 2" long teardrop shape.</p>'},
        {img:"assets/images/artwork/clay/appleblossom/appblossm3.jpg" ,
         desc: '<p>Place the 1/2" x 2" outer vein strip on the log so that one of its long sides is parallel to and extends about 1/8" past the pinched side of the log.</p>'},
        {img:"assets/images/artwork/clay/appleblossom/appblossm4.jpg",
         desc: '<p>Each half should measure about 1" long.</p>'},
        {img:"assets/images/artwork/clay/appleblossom/appblossm5.jpg",
         desc: '<p>Turn one half around so the veined side points away from the other. &nbsp;Add the 1/2" x 1" &nbsp;inner vein strip along the flat side of one of the halves, aligning the lower edges of the inner and outer veins (i.e., 1/8" past the bottom edge of the half).</p>'},
        {img: "assets/images/artwork/clay/appleblossom/appblossm6.jpg",
         desc: '<p>Place the other half against the inner vein, having flat sides together and making sure the bottom edges of the veins strips are aligned. &nbsp;Gently compress to make sure the pieces adhere. &nbsp;This is the inner petal log. &nbsp;It should be approximately 1" long.</p>'},
        {img:"assets/images/artwork/clay/appleblossom/appblossm7.jpg",
         desc: '<p>Place the lighter-colored (1" wide) end of the 9" x 1" Skinner blend along the 1/8" vein extension on one side of the inner petal log. &nbsp;Offset it slightly so you can still see the bottom of the vein.</p>'},
        {img: "assets/images/artwork/clay/appleblossom/appblossm8.jpg",
         desc: '<p>Wrap the blend over the top of the inner petal log stopping when you reach the veined extension on the other side. &nbsp;Fold the strip back on itself in order to wrap back over the top of the log going the other way. &nbsp;(You don\'t want to wrap the blend under the vein extension.)</p>'},
        {img:"assets/images/artwork/clay/appleblossom/appblossm9.jpg",
         desc: ""},
        {img:"assets/images/artwork/clay/appleblossom/appblossm10.jpg",
         desc: ""},
        {img:"assets/images/artwork/clay/appleblossom/appblossm11.jpg",
         desc: '<p><Moving back and forth from one side of the log to the other, drape the blend over the top of the inner petal log as in step 7, but stop and turn back about 1/4" sooner than the previous turn on that side. Continue until you reach the top and the blend runs out.</p>'},
        {img:"assets/images/artwork/clay/appleblossom/appblossm13.jpg",
         desc: '<p>Gently compress the draping into the inner petal log, rounding and smoothing the top and closing any gaps between layers.</p>'},
        {img:"assets/images/artwork/clay/appleblossom/appblossm14.jpg",
         desc: '<p>Wrap the 4" x 1" border strip around the petal log.</p>'},
        {img:"assets/images/artwork/clay/appleblossom/appblossm15.jpg",
         desc: '<p>Elongate (or reduce*) the petal log to 7.5 inches.</p><p>*To reduce: &nbsp;squeeze along the wrapped sides of the log, starting at the midpoint of its length and working your way towards the ends, until the clay forms a long log. &nbsp;<b>Do not</b>&nbsp;roll the clay to lengthen it.</p><p>For more information about reducing,&nbsp;<a href="http://www.polymerclaycentral.com/poleigh/reducing.html" target="_blank">click here</a></p>'},
        {img:"assets/images/artwork/clay/appleblossom/appblossm16.jpg",
         desc: '<p>As you lengthen it, pinch along the veined side of the log to form a wide teardrop shape.</p>'},
        {img:"assets/images/artwork/clay/appleblossom/appblossm17.jpg",
         desc: '<p>Cut the elongated log into five 1.5" pieces.</p>'},
        {img:"assets/images/artwork/clay/appleblossom/appblossm18.jpg",
         desc: '<p> Roll the 3/8" center ball into a 1.5-inch rope.</p>'},
        {img:"assets/images/artwork/clay/appleblossom/appblossm19.jpg",
         desc: '<p> Arrange the petal pieces around the center rope having the vein/pinched edge against the center.</p>'},
        {img:"assets/images/artwork/clay/appleblossom/appblossm20.jpg",
         desc: '<p>Gently press the petals toward the center until any gaps around the center are closed.</p>'},
        {img:"assets/images/artwork/clay/appleblossom/appblossm21.jpg",
         desc: '<p>The finished cane.</p>'},
      ]
    },
    { id: 4000002, 
      title: 'Citrus Cane', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/citrus/citrus9.jpg',
      desc: '<p>These instructions are for the auction project. &nbsp;This cane idea came from&nbsp;<a href="http://www.polymerclaycentral.com/candy_citrus.html" target="_blank">Candy\'s Citrus Cane</a>.</p><p>Materials:</p><p>1 - 1.5" diameter segment-colored ball<br />8 - 2" x 1.5" white flat strips (#3)<br />1 - 1/2" white ball for center<br />1 - 4" x 1.5" white flat strip (#2)<br />1 - 4.25" x 1.5" segment-colored flat strip (#3)<br />1 - 5" x 1.5" rind-colored flat strip (#6)</p>',
      date: '6 Jan 2013',
      content: [
        {img:"assets/images/artwork/clay/citrus/citrus1.jpg",
         desc: '<p>Roll the "segment"-colored ball into a 12" long log. &nbsp;Cut the log evenly into eight 1.5" segments.</p>'},
        {img:"assets/images/artwork/clay/citrus/citrus3.jpg",
         desc: '<p>Wrap a 2" x 1.5" white strip around each of the segments.</p>'},
        {img:"assets/images/artwork/clay/citrus/citrus4.jpg",
         desc: '<p>Pinch along one side of each segment to form a teardrop-shaped log.</p>'},
        {img:"assets/images/artwork/clay/citrus/citrus5.jpg",
         desc: '<p>Roll the 1/2" white ball into a 1.5" log for the center. &nbsp;Arrange the segments around the center with the pinched side of each segment pointing toward the center. &nbsp;Gently squeeze the arrangement together so all pieces adhere.</p>'},
        {img: "assets/images/artwork/clay/citrus/citrus6.jpg",
         desc: '<p>Wrap the 4" x 1.5" white strip around the center arrangment.</p>'},
        {img:"assets/images/artwork/clay/citrus/citrus7.jpg",
         desc: '<p>Then wrap the 4.25" x 1.5" &nbsp;segment-colored strip around the arrangement.</p>'},
        {img: "assets/images/artwork/clay/citrus/citrus8.jpg",
         desc: '<p>Finally, wrap the rind-colored (darker) strip around the arrangement.</p>'},
        {img:"assets/images/artwork/clay/citrus/citrus9.jpg",
         desc: "<p>The finished cane.</p>"}
      ]
    },
    { id: 4000003, 
      title: 'Daisy Cane', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/daisy/daisy9.jpg',
      desc: '<p>These instructions are for the auction project.</p><p>Materials:</p><p>1 - 9" x 2.5" Skinner blend (petals)<br />1 - 5" x 3" flat strip for petal outline<br />1 - 1/2" ball for flower center</p>',
      date: '19 Jan 2013',
      content: [
        {img:"assets/images/artwork/clay/daisy/daisy1.jpg",
         desc: '<p>Starting at the lighter-colored end of the Skinner blend, fold the clay back-and-forth "accordian" style with each fold being about 1/2 to 3/4 inch wide.</p>'},
        {img:"assets/images/artwork/clay/daisy/daisy3.jpg" ,
         desc: 'The folded clay will look something like the "accordian" in the image to the left. &nbsp;While maintaining the narrow oval shape as shown in this and the next picture, gently compress the accordian until the folds are pressed together with no gaps. &nbsp;As you compress it, the height and width of the accordian will become smaller while the length will increase. &nbsp;The result should be about 5/8" wide x 1.5" tall x 3" long.</p>'},
        {img:"assets/images/artwork/clay/daisy/daisy4.jpg",
         desc: '<p>Wrap the 5" x 3" flat piece of outline-colored clay around the compressed accordian. &nbsp;Then gently reduce* the accordian to a length of 12 inches. &nbsp;</p><p>*To reduce: &nbsp;squeeze along the wrapped sides of the accordian, starting at the midpoint of its length and working your way towards the ends, until the clay forms a long log. &nbsp;Squeeze all the way around but vary the pressure so that the log maintains its oval shape with the light color at the top and the dark color at the bottom. &nbsp;Do not roll the clay to lengthen it. &nbsp;For more information about reducing,&nbsp;<a href="http://www.polymerclaycentral.com/poleigh/reducing.html" target="_blank">click here</a>.</p>'},
        {img:"assets/images/artwork/clay/daisy/daisy5.jpg",
         desc: '<p>Cut the clay log into three 4-inch segments.</p>'},
        {img: "assets/images/artwork/clay/daisy/daisy6.jpg",
         desc: '<p>Arrange the three segments so that the light-colored sides/ends (of their centers) &nbsp;are together as shown in the picture. &nbsp;If necessary, pinch lightly along the joined sides to make sure the segments stick together.</p>'},
        {img:"assets/images/artwork/clay/daisy/daisy7.jpg",
         desc: '<p>Cut the joined segments into four 1-inch pieces.</p>'},
        {img: "assets/images/artwork/clay/daisy/daisy8.jpg",
         desc: '<p>Arrange the four pieces so that their joined sides (and the light-colored sides of their centers) all face each other. &nbsp;These are the petals of the daisy.</p>'},
        {img:"assets/images/artwork/clay/daisy/daisy9.jpg",
         desc: "<p>Roll the remaining 1/2\" ball into a 1-inch log and place inside the center of the petal arrangement. &nbsp;Gently squeeze the pieces together so there are no gaps between the petals and the center.</p>"},
      ]
    },
    { id: 4000004, 
      title: 'Eye-shaped Cane', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/eyeleaf/eyeleaf16.jpg',
      desc: '<p>These instructions are for the auction project.</p><p>Materials:</p><p>1 - 3" x 9" Skinner Blend (#5)<br />1 - 6" x 1" vein strip<br />1 - 6" x 1" border strip</p>" x 1" flat Skinner blend for outer petals<br /> 1 - 4" x 1" flat outline strip<br /> 1 - 3/8" ball for center</span></p>',
      date: '19 Jan 2013',
      content: [
        {img:"assets/images/artwork/clay/eyeleaf/eyeleaf1.jpg",
         desc: '<p>Starting at the lighter-colored end of the Skinner blend, fold the clay back-and-forth "accordian" style with each fold being about 1/2 to 3/4 inch wide.</p>'},
        {img:"assets/images/artwork/clay/eyeleaf/eyeleaf2.jpg",
         desc: ''},
        {img:"assets/images/artwork/clay/eyeleaf/eyeleaf3.jpg" ,
         desc: '<p>The folded clay will look something like the "accordian" in the preceding image.</p><hr>'},
        {img:"assets/images/artwork/clay/eyeleaf/eyeleaf5.jpg",
         desc: '<p>Gently compress the accordian until the folds are pressed together with no gaps.&nbsp;&nbsp;It\'s dimensions should approximately 3/4" wide x 1.5" tall x 3" long.</p><hr>'},
        {img: "assets/images/artwork/clay/eyeleaf/eyeleaf6.jpg",
         desc: '<p>Cut the accordian in half perpendicular to its length to make two shorter, matching 3/4" x 1.5" x 1.5" accordians (each with a light side and a dark side).</p><hr>'},
        {img:"assets/images/artwork/clay/eyeleaf/eyeleaf7.jpg",
         desc: '<p>Set the accordians side-by-side with both of their lighter-colored sides facing left. &nbsp;Shape the two accordians into half-circles so that the ligher-colored side of one half is on the curved side while the lighter-colored side of the other half is on the straight side. &nbsp;(See picture.) &nbsp;These two halves will become the inner leaf.</p>'},
        {img: "assets/images/artwork/clay/eyeleaf/eyeleaf8.jpg",
         desc: '<hr>'},
        {img:"assets/images/artwork/clay/eyeleaf/eyeleaf9.jpg",
         desc: "<p>To make the leaf veins, slice one leaf half into three pieces by cutting an upward angle from the flat side to the curved side.</p><hr>"},
        {img:"assets/images/artwork/clay/eyeleaf/eyeleaf10.jpg",
         desc: "<p>Cut small slices from the 6\" x 1\" flat vein strip to put between the leaf pieces as shown in the picture. &nbsp;Be sure to align the vein's edge with the flat edge of the leaf piece. &nbsp;The vein slice should go about two thirds of the way from the flat inner edge to the outer curved edge of the leaf.</p><hr>"},
        {img:"assets/images/artwork/clay/eyeleaf/eyeleaf11.jpg",
         desc: '<p>Repeat steps 6 and 7 on the other leaf half. &nbsp;Gently press the pieces of each half back into place to re-form the two separate leaf halves.</p><hr>'},
        {img:"assets/images/artwork/clay/eyeleaf/eyeleaf12.jpg",
         desc: '<p>Cut the remaining vein strip to fit between the two leaf halves. &nbsp;Press it against the flat side of one half, making sure that its short edge aligns with the bottom of the leaf half. &nbsp;(The bottom of the leaf can be determined by looking at the vein slices, which angle down toward the bottom.)</p><hr>'},
        {img:"assets/images/artwork/clay/eyeleaf/eyeleaf16.jpg",
         desc: '<p>Gently press the two halves together along their flat sides to make the leaf. &nbsp;Shape the leaf into a teardrop shape by gently pinching its top to a point. &nbsp;Wrap the inner leaf with the border strip to outline the leaf.</p>'}
      ]
    },
    { id: 4000005, 
      title: 'Five Rounded-Petal Flower Cane', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/rounded/rounded12.jpg',
      desc: '<p>These instructions are for the auction project.</p><p>Materials:</p><p>1 - 6" x 3" Skinner blend strip (#7)<br />1 - 4.5" x 3" flat outline strip (#4)<br />1 - 3/8" x 3" flat vein strip (#4)<br />1 - 1/2" ball for flower center</p>',
      date: '7 Jan 2013',
      content: [
        {img:"assets/images/artwork/clay/rounded/rounded2.jpg",
         desc: '<p>Beginning at the lighter-colored end of the Skinner blend, roll the strip up like a jelly roll.</p>'},
        {img:"assets/images/artwork/clay/rounded/rounded3.jpg" ,
         desc: '<p>Wrap the 4.5" x 3" outline strip around the jelly roll.</p>'},
        {img:"assets/images/artwork/clay/rounded/rounded4.jpg",
         desc: '<p>Make a cut from the top of the jelly roll to its center and open the gap slightly.</p>'},
        {img:"assets/images/artwork/clay/rounded/rounded5.jpg",
         desc: '<p>Place the 3/8" x 3" vein strip in the gap, aligning the top edges.</p>'},
        {img: "assets/images/artwork/clay/rounded/rounded6.jpg",
         desc: '<p>Close the gap around the vein strip.</p>'},
        {img:"assets/images/artwork/clay/rounded/rounded7.jpg",
         desc: '<p>Squeeze around the roll, beginning in its middle and working your way towards the ends, to elongate it 8.75 inches. &nbsp;<strong>DON\'T&nbsp;</strong>roll it on the desk because it will distort the vein strip.</p>'},
        {img: "assets/images/artwork/clay/rounded/rounded8.jpg",
         desc: '<p>Cut the elongated roll into five 1.75-inch pieces. &nbsp;These are the petals.</p>'},
        {img:"assets/images/artwork/clay/rounded/rounded9.jpg",
         desc: "<p>Roll the remaining 1/2\" center ball into a 1.75-inch log shape.</p>"},
        {img:"assets/images/artwork/clay/rounded/rounded10.jpg",
         desc: "<p>Arrange the petals around the center so that their vein lines are against the center.</p>"},
        {img:"assets/images/artwork/clay/rounded/rounded11.jpg",
         desc: '<p>There may be gaps between some of the petals and the center. &nbsp;In this case, place the cane across the palm of your hand, wrap your fingers over it and very gently squeeze in to press the petals in against the center. &nbsp;Turn the cane in your hand to make sure the flower shape remains balanced. &nbsp;Don\'t press so hard that the petals lose their rounded appearance. &nbsp;Also, don\'t roll the cane on the desk.</p>'},
        {img:"assets/images/artwork/clay/rounded/rounded12.jpg",
         desc: '<p>The completed cane will look similar to this one.</p>'},
      ]
    },
    { id: 4000006, 
      title: 'Five Triangle-Petal Flower Cane', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/triangle5/tri5-9.jpg',
      desc: '<p>These instructions are for the auction project.</p><p>Materials (Clay):</p><p>1 - 1.5" ball for petals<br />5 - 1.5" x 1.25" flat outline strips (to outline petals)<br />1 - 1.25" ball for filler between petals<br />1 - 3/8" ball for flower center</p>',
      date: '8 Jan 2013',
      content: [
        {img:"assets/images/artwork/clay/triangle5/tri5-1.jpg",
         desc: '<p>Roll the 1.5" petal ball into a 6.25" log. &nbsp;Keep the diameter of the log consistent along its length..</p>'},
        {img:"assets/images/artwork/clay/triangle5/tri5-2.jpg",
         desc: '<p>Cut the log into five 1.25" pieces.</p>'},
        {img:"assets/images/artwork/clay/triangle5/tri5-3.jpg" ,
         desc: '<p>Wrap each of the pieces with a 1.5" x 1.25" outline strip.</p>'},
        {img:"assets/images/artwork/clay/triangle5/tri5-4.jpg",
         desc: '<p>Roll the 3/8" center ball into a 1.25" long rope.</p>'},
        {img:"assets/images/artwork/clay/triangle5/tri5-5.jpg",
         desc: '<p>Turn one half around so the veined side points away from the other. &nbsp;Add the 1/2" x 1" &nbsp;inner vein strip along the flat side of one of the halves, aligning the lower edges of the inner and outer veins (i.e., 1/8" past the bottom edge of the half).</p>'},
        {img: "assets/images/artwork/clay/triangle5/tri5-6.jpg",
         desc: '<p>Roll the 1.25" filler ball into a 6.25" log keeping the diameter of the log consistent along its length. &nbsp;Slice the log into five 1.25" pieces.</p>'},
        {img:"assets/images/artwork/clay/triangle5/tri5-7.jpg",
         desc: '<p>Shape each filler piece into a flattened teardrop shape.</p>'},
        {img: "assets/images/artwork/clay/triangle5/tri5-8.jpg",
         desc: '<p>Alternating petal pieces with filler pieces, arrange the petals and fillers around the center rope.</p>'},
        {img:"assets/images/artwork/clay/triangle5/tri5-9.jpg",
         desc: "If necessary, gently and evenly compress the arrangement from the outside toward the center to close any gaps."}
      ]
    },
    { id: 4000007, 
      title: 'Heart-shaped Leaf Cane', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/heartleaf/heart12.jpg',
      desc: '<p>These instructions are for the auction project.</p><p>Materials:</p><p>1 - 9" x 3" Skinner blend strip<br />1 - 4" x 3" flat outline strip',
      date: '19 Jan 2013',
      content: [
        {img:"assets/images/artwork/clay/heartleaf/heart1.jpg",
         desc: '<p>Slice the 9" x 3" &nbsp;Skinner blend strip widthwise into 5/8" x 3" strips.</p>'},
        {img:"assets/images/artwork/clay/heartleaf/heart2.jpg",
         desc: '<hr>'},
        {img:"assets/images/artwork/clay/heartleaf/heart3.jpg" ,
         desc: '<p>Starting at one end of the sliced blend, stack the strips in order.</p><hr>'},
        {img:"assets/images/artwork/clay/heartleaf/heart4.jpg",
         desc: '<p>Gently press down on the top of the stack so that the strips stick together, then press in from the side to shape the stack into about a 1.25" tall x 1/2" wide x 3" long narrow block. &nbsp;(The picture shows the block from the side. &nbsp;The next pictures shows it from one end.)</p><hr>'},
        {img:"assets/images/artwork/clay/heartleaf/heart5.jpg",
         desc: '<p>Wrap the block with the 4" x 3" outline strip.</p><hr>'},
        {img: "assets/images/artwork/clay/heartleaf/heart6.jpg",
         desc: '<p>Elongate the wrapped block to approximately 1/4" wide x 1" tall x 6" long by gently squeezing in along its sides. &nbsp;Force the block to grow longer by pressing in on its top and bottom as necessary so that it doesn\'t &nbsp;become too tall.</p><hr>'},
        {img:"assets/images/artwork/clay/heartleaf/heart7.jpg",
         desc: '<p>Cut the elongated block into four 1.5"-long pieces.</p><hr>'},
        {img: "assets/images/artwork/clay/heartleaf/heart8.jpg",
         desc: '<p>Arrange the pieces side-to-side with the <strong>light-colored</strong> ends together as shown.</p><hr>'},
        {img:"assets/images/artwork/clay/heartleaf/heart9.jpg",
         desc: "<p>Pinch the <strong>light-colored</strong> ends together to form a point. &nbsp;Gently squeeze along the sides of the pieces to join them. &nbsp;Shape the dark-colored ends into a curve so the overall shape of the joined pieces is a teardrop.</p><hr>"},
        {img:"assets/images/artwork/clay/heartleaf/heart10.jpg",
         desc: "<p>Cut the resulting teardrop-shaped log evenly in half.</p>"},
        {img:"assets/images/artwork/clay/heartleaf/heart11.jpg",
         desc: '<hr>'},
        {img:"assets/images/artwork/clay/heartleaf/heart12.jpg",
         desc: '<p>Align the two halves so that they are mirror images with the light-colored points together. &nbsp;Gently press them together to form a heart-shaped leaf.</p>'}
      ]
    },
    { id: 4000008, 
      title: 'Hydrangea Cane', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/hydrangea/hydrangea10.jpg',
      desc: '<p>These instructions are for the auction project.</p><p>Materials:</p><p>1 - 8" x 3" 80/20 blended strip (#7)<br />3 - 1/4" x 3" flat vein strip (#3)<br />1 - 4" x 3" flat outline strip (#4)<br />1 - 3/8" ball in flower center color</p>',
      date: '7 Jan 2013',
      content: [
        {img:"assets/images/artwork/clay/hydrangea/hydrangea1.jpg",
         desc: '<p>Beginning at the narrow, dark-colored end of the blended strip, roll the strip into a jelly roll.</p>'},
        {img:"assets/images/artwork/clay/hydrangea/hydrangea2.jpg",
         desc: '<p>Set the jelly roll so that the light-colored portion is on the top. &nbsp;Make a slice down from the top through the middle of the light-colored section to the center of the roll.</p>'},
        {img:"assets/images/artwork/clay/hydrangea/hydrangea3.jpg" ,
         desc: '<p>Place one of the 3/8" x 3" vein strips inside the sliced opening, aligning the long edge of the strip with the outside of the roll.</p><p>Repeat the slice-fill process two more times: once 1/4" to the left of the first slice...</p>'},
        {img:"assets/images/artwork/clay/hydrangea/hydrangea4.jpg",
         desc: '<p>and once 1/4" to the right of the first slice./p>'},
        {img:"assets/images/artwork/clay/hydrangea/hydrangea5.jpg",
         desc: '<p>Wrap the roll with the 4" x 3" outline strip.</p>'},
        {img: "assets/images/artwork/clay/hydrangea/hydrangea6.jpg",
         desc: '<p>Reduce the roll to a 6" log.&nbsp;</p><p>*To reduce: &nbsp;squeeze the roll in your hand and fingers starting in the middle and working your way towards the ends. &nbsp;<strong>DON\'T</strong> roll the clay to lengthen it. &nbsp;Try to keep the ends of the roll from becoming too distorted by pressing in on them as you work your way to the ends. &nbsp;For more information about reducing,&nbsp;<a href="http://www.polymerclaycentral.com/poleigh/reducing.html" target="_blank">click here</a>.</p>'},
        {img:"assets/images/artwork/clay/hydrangea/hydrangea7.jpg",
         desc: '<p>Cut the reduced log into four 1.5"-long pieces.</p>'},
        {img: "assets/images/artwork/clay/hydrangea/hydrangea8.jpg",
         desc: '<p>Pinch the side of the roll opposite the veins slightly to form a candy-corn shaped log. &nbsp;These are the hydrangea\'s petals.</p>'},
        {img:"assets/images/artwork/clay/hydrangea/hydrangea9.jpg",
         desc: "<p>Roll the 3/8\" center ball into a log that is the same length as the petal rolls. &nbsp;Arrange the four petal rolls evenly around the center with the pinched sides pointing toward the center.</p>"},
        {img:"assets/images/artwork/clay/hydrangea/hydrangea10.jpg",
         desc: "<p>Gently squeeze the roll as necessary to make sure all the petals adhere in the center while maintaining their individual curves on the outside. &nbsp;(See picture.)</p>"}
      ]
    },
    { id: 4000009, 
      title: 'Ladybug Cane', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/ladybug/ladybug9.jpg',
      desc: '<p><p>These instructions are for the auction project.</p><p>Materials:</p><p>1 - 1" ball of body color<br />3 - 3/8" black balls for dots<br />4 - 1/2" balls in body color<br />1 - 6" x 2.5" flat strip in body color (#7)<br />1 - 1.5" x 1.25" black flat strip for wing divider (#6)<br />1 - 3/4" black ball for the head</p>',
      date: '7 Jan 2013',
      content: [
        {img:"assets/images/artwork/clay/ladybug/ladybug1.jpg",
         desc: '<p>Roll the 1" ball of body color clay into a 3" long log that is slightly flat on the bottom. &nbsp;Also, roll the three 3/8" black "dot" balls into 3" long ropes.</p>'},
        {img:"assets/images/artwork/clay/ladybug/ladybug2.jpg",
         desc: '<p>Arrange the three black ropes along the body-colored log with one rope centered on top and the other two placed on either side of the first, halfway between it and the table top (as shown in the picture). &nbsp;These black ropes will be the dots on the ladybug\'s back.</p>'},
        {img:"assets/images/artwork/clay/ladybug/ladybug3.jpg" ,
         desc: '<p>Roll the four 1/2" body-colored balls into 3" long ropes.</p>'},
        {img:"assets/images/artwork/clay/ladybug/ladybug4.jpg",
         desc: '<p>Place the body-colored ropes on each side of the black ropes to act as fillers.</p>'},
        {img:"assets/images/artwork/clay/ladybug/ladybug5.jpg",
         desc: '<p>Fold the 6" x 2.5" body-colored strip in half so that it is 3" x 2.5". &nbsp;Place this folded flat over the black and orange ropes, completely covering them. &nbsp;This arrangement forms the wing of the ladybug.</p>'},
        {img: "assets/images/artwork/clay/ladybug/ladybug6.jpg",
         desc: '<p>Cut width-wise across the wing arrangement so that you have two matching wings, both about 1.5" long. &nbsp;Turn the two halves on their sides with dots facing up.</p>'},
        {img:"assets/images/artwork/clay/ladybug/ladybug7.jpg",
         desc: '<p>Place the black, 1.5" x 1.25" wing divider strip on the flat side of one of the wing halves. Place the flat side of the other wing against the exposed side of the wing divider to form the ladybug\'s body.</p>'},
        {img: "assets/images/artwork/clay/ladybug/ladybug8.jpg",
         desc: '<p>For the ladybug\'s head, shape the 3/4" black ball into a 1.5"-long half-circle shaped log. &nbsp;Place the flat side of the log against the ladybug body at one end of the wing divider.</p>'},
        {img:"assets/images/artwork/clay/ladybug/ladybug9.jpg",
         desc: "<p>Gently press the body and head together. &nbsp;Also press around the outside of the body to close any gaps in the wings.</p>"}
      ]
    },
    { id: 4000010, 
      title: 'Rose Cane', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/rose/rose16.jpg',
      desc: '<p>These instructions are for the auction project.</p><p>Materials:</p><p>1 - 8" x 3" Skinned blend strip (#7)<br />1 - 5" x 3" flat outline strip (#6)</p>- 4" x 1" flat outline strip<br /> 1 - 3/8" ball for center</span></p>',
      date: '19 Jan 2013',
      content: [
        {img:"assets/images/artwork/clay/rose/rose2.jpg",
         desc: '<p>Starting at the 3" long, light-colored end of the Skinner blend, roll the strip into a jelly roll.</p>'},
        {img:"assets/images/artwork/clay/rose/rose3.jpg" ,
         desc: '<hr>'},
        {img:"assets/images/artwork/clay/rose/rose4.jpg",
         desc: '<p>Wrap the jelly roll in the 5" x 3" flat outline strip.</p><hr>'},
        {img:"assets/images/artwork/clay/rose/rose5.jpg",
         desc: '<p>Elongate (or \'reduce\') the jelly roll to 7.5 inches by squeezing it from the middle toward the ends. <strong>DON\'T</strong> roll the clay to elongate it. &nbsp;For more information about reducing,&nbsp;<a href="http://www.polymerclaycentral.com/poleigh/reducing.html" target="_blank">click here</a>.</p><hr>'},
        {img: "assets/images/artwork/clay/rose/rose6.jpg",
         desc: '<p>Cut the elongated clay roll into six 1.25-inch pieces.</p><hr>'},
        {img:"assets/images/artwork/clay/rose/rose7.jpg",
         desc: '<p>Take one of the pieces and flatten it down, pinching it almost to a point along one edge.</p><hr>'},
        {img: "assets/images/artwork/clay/rose/rose8.jpg",
         desc: '<p>Roll the flattened piece from its wider edge to its pointed edge to form the rose\'s center as shown in the pictures.</p>'},
        {img:"assets/images/artwork/clay/rose/rose9.jpg",
         desc: "<hr>"},
        {img:"assets/images/artwork/clay/rose/rose10.jpg",
         desc: "<p>Shape each of the remaining five pieces into an \"apostrophe\" shape. &nbsp;They are the petals of the rose.</p>"},
        {img:"assets/images/artwork/clay/rose/rose11.jpg",
         desc: ''},
         {img:"assets/images/artwork/clay/rose/rose12.jpg",
         desc: "<hr>"},
        {img:"assets/images/artwork/clay/rose/rose13.jpg",
         desc: '<p>Start arranging the petals around the center: take the first petal and turn it on its side so that its pointed edge faces the same direction as the pointed side in the center roll. &nbsp;(In the picture, they both point counterclockwise.) Press the side of the petal\'s rounded end against the center as shown in the picture.</p><hr>'},
        {img:"assets/images/artwork/clay/rose/rose15.jpg",
         desc: '<p>Repeat step 8 with the remaining four petals, spacing them evenly around the center. &nbsp;As &nbsp;you add each petal, place its rounded end under the flattened end of the previous piece as shown.</p><hr>'},
        {img:"assets/images/artwork/clay/rose/rose16.jpg",
         desc: '<p>Gently press the pointed edges of the petals down over the rounded end of the next petal as shown.</p>'}
      ]
    },
    { id: 4000011, 
      title: 'Shady Flower Cane', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/shady/shady11.jpg',
      desc: '<p>These instructions are for the auction project. &nbsp;The idea for the cane originated from&nbsp;<a href="http://www.polymerclaycentral.com/shady_flower.html" target="_blank">Naama Zamir</a>.</p><p>Materials:</p><p>1 - 12" x 3" Skinner blend strip (#4)<br />1 - 4" x 1.5" flat outline strip (#4)<br />1 - 3/8" ball for flower center</p>',
      date: '7 Jan 2013',
      content: [
        {img:"assets/images/artwork/clay/shady/shady1.jpg",
         desc: '<p>Starting at the lighter-colored end of the Skinner blend, fold the clay back-and-forth "accordian" style with each fold being about 1/2 to 3/4 inch wide. &nbsp;The folded clay will look something like the "accordian" in the second picture to the left.</p>'},
        {img:"assets/images/artwork/clay/shady/shady2.jpg",
         desc: '<hr>'},
        {img:"assets/images/artwork/clay/shady/shady3.jpg" ,
         desc: '<p>Set the accordian on the table on its long dark side and gently press down along its top (i.e., light colored side) just until the folds are pressed together with no gaps.</p><hr>'},
        {img:"assets/images/artwork/clay/shady/shady4.jpg",
         desc: '<p>Cut the accordian evenly into three 1-inch wide pieces, slicing down from the light to the dark colored sides.</p><hr>'},
        {img:"assets/images/artwork/clay/shady/shady5.jpg",
         desc: '<p>Take one piece and turn it so that the zig-zag pattern of its folds face you, then shape it so that the zig-zag side looks like an 1.5" long elongated diamond. &nbsp;As you shape it, keep its height at about 1.5" tall by pressing on its zig-zag sides as necessary (which will also smooth them out).</p><hr>'},
        {img: "assets/images/artwork/clay/shady/shady6.jpg",
         desc: '<p>Take each of the remaining two pieces and again turn them so the zig-zag faces you. Shape them into 1.5" long half moon (or boomerang) shapes that are about 1.5" tall. &nbsp;Arrange the three pieces on the table as shown in the picture so that the light-colored end of the center diamond is opposite the light-colored ends of the two half moons.</p><hr>'},
        {img:"assets/images/artwork/clay/shady/shady7.jpg",
         desc: '<p>Press the three pieces together until they adhere and form an "eye" shape. &nbsp;Wrap the 4" x 1.5" outline strip around the outside of the eye.</p><hr>'},
        {img: "assets/images/artwork/clay/shady/shady8.jpg",
         desc: '<p>Elongate (or "reduce") the eye-shaped clay until it is at least 5 inches long by squeezing it gently on its sides between your fingers. &nbsp;<strong>DON\'T</strong> roll the clay on the table to make it longer as this will distort the image in the center. &nbsp;As you squeeze the sides, try to keep the ends flat to minimize the distortion that occurs on the ends.</p><p><a href="http://www.polymerclaycentral.com/poleigh/reducing.html" target="_blank">These instructions</a>&nbsp;show you how to reduce the clay with as little distortion/waste as possible.</p><p>Once the clay is elongated, trim off any <strong>excessive</strong> distortion if necessary (don\'t cut off more than 1/2" because you need at least 5" of remaining length), then cut the remainder into five even pieces.</p><hr>'},
        {img:"assets/images/artwork/clay/shady/shady9.jpg",
         desc: "<p>Shape each piece into a diamond shape. &nbsp;These pieces are the flower petals. &nbsp;Arrange the petals so that the light-colored ends of their <strong>center</strong> sections all face toward the center.</p><hr>"},
        {img:"assets/images/artwork/clay/shady/shady10.jpg",
         desc: "<p>Roll the 3/8\" ball of center color clay into a rope that's the same length as the height of the petals.</p><hr>"},
        {img:"assets/images/artwork/clay/shady/shady11.jpg",
         desc: '<p>Place the center into the gap in the middle of the petal arrangemet, then gently press the petals inward toward the center until any gaps close and the petals and center are joined.</p>'},
      ]
    } ,
    { id: 4000012, 
      title: 'Six Triangle-Petal Flower Cane', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/striped6tri/striped6tri7.jpg',
      desc: '<p>These instructions are for the auction project.</p><p>Materials (Clay):</p><p>1 - 6" x 2.5" flat strip for inner stripes (#5)<br />1 - 6.75" x 2.5" flat strip for outer stripes (#5)<br />6 - 2" x 1" flat strips for petal outlines (#5)<br />1 - 3/8" ball for center</p>',
      date: '7 Jan 2013',
      content: [
        {img:"assets/images/artwork/clay/striped6tri/striped6tri1.jpg",
         desc: '<p>Lay the 6" x 2.5" strip (for inner stripes) and the 6.75" x 2.5" strip (for outer stripes) on the desk. &nbsp;Slice both strips into 3/4" wide x 2.5" long pieces (by cutting parallel to their short sides). &nbsp;You should have eight pieces for the inner stripes and nine pieces for the outer stripes.</p>'},
        {img:"assets/images/artwork/clay/striped6tri/striped6tri2.jpg",
         desc: '<p>Beginning with an outer stripe piece, stack the pieces alternating between the outer and inner stripe colors. &nbsp;The top and bottom pieces should be the outer stripe color.</p>'},
        {img:"assets/images/artwork/clay/striped6tri/striped6tri3.jpg" ,
         desc: '<p>Holding the stack so the lines run horizontally, pinch in on the sides to bring the ends of the lines together (and to form an eye shape).</p><p>Gently elongate (or "reduce") the stack by squeezing it between your fingers. &nbsp;Press mostly from the top and bottom to cause the stack to lenghten into a rope -- you\'ll need to pinch the sides occasionally to keep the eye shape. &nbsp;<strong>Do not</strong>&nbsp;roll the stack as this will twist the stripes!</p><p><a href="http://www.polymerclaycentral.com/poleigh/reducing.html" target="_blank">These instructions</a> provide more details about how to reduce the clay with as little distortion/waste as possible.</p>'},
        {img:"assets/images/artwork/clay/striped6tri/striped6tri4.jpg",
         desc: '<p>Set the rope on one of the pinched edges with stripes vertical. &nbsp;Press down slightly to flatten the bottom a little. &nbsp;Cut the rope into six 1-inch pieces. &nbsp;These pieces will become the petals of the flower.</p>'},
        {img:"assets/images/artwork/clay/striped6tri/striped6tri5.jpg",
         desc: '<p>Wrap each petal piece with a 2" x 1" outline strip. &nbsp;Then shape the petal into a triangle with the striped ends facing the top of the triangle as shown.</p>'},
        {img: "assets/images/artwork/clay/striped6tri/striped6tri6.jpg",
         desc: '<p>Roll the remaining 3/8" ball into a 1" long rope to use as the center of the flower. &nbsp;Arrange the petals around the center so that the top of the triangle and the stripes in the petals point toward the center.</p>'},
        {img:"assets/images/artwork/clay/striped6tri/striped6tri7.jpg",
         desc: '<p>Gently press from the outsides of opposite petals to make sure they adhere to the center and any gaps are closed. &nbsp;Press each petal evenly so the finished flower is balanced.</p>'}
      ]
    },
    { id: 4000013, 
      title: 'Spiral Cane', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/spiral/spiral5.jpg',
      desc: '<p>These instructions are for the auction project.</p><p>Materials:</p><p>1 - 7" x 1.5" black flat strip (#5)<br />1 - 6" x 1.5" solid colored strip (#5)<br />1 - 6" x 1.5" Skinner blend strip (#6)<br />1 - 1/2" ball for center</p>',
      date: '7 Jan 2013',
      content: [
        {img:"assets/images/artwork/clay/spiral/spiral1.jpg",
         desc: '<p>Roll the 1/2" center ball into an even rope that is as long as the black flat strip is wide (approximately 1.5").</p>'},
        {img:"assets/images/artwork/clay/spiral/spiral2.jpg",
         desc: '<p>Place the center rope at one end of the black flat strip and roll the black strip around the rope one time.</p>'},
        {img:"assets/images/artwork/clay/spiral/spiral3.jpg" ,
         desc: '<p>Layer the solid-colored flat strip over the rest of the black strip, leaving a 3/16" gap between the center roll and the end of the solid-colored strip. &nbsp;Then layer the Skinner blend on top of the light-colored strip, placing it so that its light-colored end is closest to the center roll and so that about 1/8" of the solid-colored strip is exposed as shown in the picture.</p>'},
        {img:"assets/images/artwork/clay/spiral/spiral4.jpg",
         desc: '<p>Carefully roll the center roll over the layered strips, keeping the edges aligned, to form a jelly roll.</p>'},
        {img:"assets/images/artwork/clay/spiral/spiral5.jpg",
         desc: '<p>The finished spiral cane should look similar to this picture.</p>'}
      ]
    },
    { id: 4000014, 
      title: 'Striped 5-Petal Flower Cane', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/striped5petal/striped9.jpg',
      desc: '<p>These instructions are for the auction project.</p><p>Materials:</p><p>1 - 9" x 2.5" Skinner blend strip (petals)<br />1 - 5" x 3" flat strip for petal outline<br />1 - 3/8" ball for flower center</p>',
      date: '7 Jan 2013',
      content: [
        {img:"assets/images/artwork/clay/striped5petal/striped1.jpg",
         desc: '<p>Starting at the lighter-colored end of the Skinner blend, fold the clay back-and-forth "accordian" style with each fold being about 1/2 to 3/4 inch wide.</p>'},
        {img:"assets/images/artwork/clay/striped5petal/striped2.jpg",
         desc: '<hr>'},
        {img:"assets/images/artwork/clay/striped5petal/striped3.jpg" ,
         desc: '<p>The folded clay will look something like the "accordian" in the image to the left. &nbsp;While maintaining the oval shape as shown in this and the next picture, gently compress the accordian until the folds are pressed together with no gaps. &nbsp;As you compress it, the height and width of the accordian will become smaller while the length will increase. &nbsp;The result should be about 5/8" x 1.5" x 3".</p><hr>'},
        {img:"assets/images/artwork/clay/striped5petal/striped4.jpg",
         desc: '<p>Wrap the 5" x 3" flat piece of outline-colored clay around the compressed accordian. &nbsp;Then gently reduce* the accordian to a length of 12 inches. &nbsp;</p><p>*To reduce: &nbsp;squeeze along the wrapped sides of the accordian, starting at the midpoint of its length and working your way towards the ends, until the clay forms a long log. &nbsp;Squeeze all the way around but vary the pressure so that the log maintains its oval shape with the light color at the top and the dark color at the bottom. &nbsp;<strong>Do not</strong> roll the clay to lengthen it. &nbsp;For more information about reducing,&nbsp;<a href="http://www.polymerclaycentral.com/poleigh/reducing.html" target="_blank">click here</a>.</p><hr>'},
        {img:"assets/images/artwork/clay/striped5petal/striped5.jpg",
         desc: '<p>Cut the clay log into four 3-inch segments.</p><hr>'},
        {img: "assets/images/artwork/clay/striped5petal/striped6.jpg",
         desc: '<p>Arrange the four segments side-to-side so that the light-colored portion of their centers all face the same direction as shown in the picture.</p><hr>'},
        {img:"assets/images/artwork/clay/striped5petal/striped7.jpg",
         desc: '<p>Shape the segments into an oval, making sure the lines in the center run from the top of the oval to bottom. &nbsp;Reduce (as in step #3) the clay to a 7.5-inch long, oval-shaped rope. &nbsp;Do not roll the clay as this will distort the pattern running through it)</p><hr>'},
        {img: "assets/images/artwork/clay/striped5petal/striped8.jpg",
         desc: '<p>Cut the rope into five 1.5" segments. &nbsp;These segments are the petals of the flower.</p><hr>'},
        {img:"assets/images/artwork/clay/striped5petal/striped9.jpg",
         desc: "<p>Roll the 3/8\" center ball into a rope the same length as the height of the petals. &nbsp;Arrange the petals around the center rope so that the light-colored portion of each inner petal faces the center. &nbsp;(The lines inside the petals should also point toward the center.) &nbsp;You may need to pinch the center-facing edge of each petal so that they will all fit around the center. &nbsp;Gently squeeze the petals toward the center to close any gaps.</p>"}
      ]
    },
    { id: 4000015, 
      title: 'Striped Pinwheel Flower Cane', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/striped6tear/striped6tear7.jpg',
      desc: '<p>These instructions are for the auction project.</p><p>Materials (Clay):</p><p>1 - 6" x 2.5" flat strip for inner stripes (#5)<br />1 - 6.75" x 2.5" flat strip for outer stripes (#5)<br />6 - 2" x 1" flat strips for petal outlines (#5)<br />1 - 1.5" x 1" Skinner blend strip for center (#4)</p>',
      date: '78 Jan 2013',
      content: [
        {img:"assets/images/artwork/clay/striped6tear/striped6tear1.jpg",
         desc: '<p>Lay 6" x 2.5" strip (for inner stripes) and the 6.75" x 2.5" strip (for outer stripes) on the desk. &nbsp;Slice both strips into 3/4" wide x 2.5" long pieces (by cutting parallel to their short sides). &nbsp;You should have eight pieces for the inner stripes and nine pieces for the outer stripes.</p>'},
        {img:"assets/images/artwork/clay/striped6tear/striped6tear2.jpg",
         desc: '<p>Beginning with an outer stripe piece, stack the pieces alternating between the outer and inner stripe colors. &nbsp;The top and bottom pieces should be the outer stripe color.</p>'},
        {img:"assets/images/artwork/clay/striped6tear/striped6tear3.jpg" ,
         desc: '<p>Holding the stack so the lines run horizontally, pinch in on the sides to bring the ends of the lines together (and to form an eye shape).</p><p>Gently elongate (or "reduce") the stack by squeezing it between your fingers. &nbsp;Press mostly from the top and bottom to cause the stack to lenghten into a rope -- you\'ll need to pinch the sides occasionally to keep the eye shape. &nbsp;<strong>Do not</strong> roll the stack as this will twist the stripes!</span></p><p><a href="http://www.polymerclaycentral.com/poleigh/reducing.html" target="_blank">These instructions</a> provide more details about how to reduce the clay with as little distortion/waste as possible.</p>'},
        {img:"assets/images/artwork/clay/striped6tear/striped6tear4.jpg",
         desc: '<p>Set the rope on one of the pinched edges with stripes vertical. &nbsp;Press down slightly to flatten the bottom a little. &nbsp;</span>Cut the rope into six 1-inch pieces.</p>'},
        {img:"assets/images/artwork/clay/striped6tear/striped6tear5.jpg",
         desc: '<p>To form the petals, shape each piece into a teardrop with the striped ends facing up and down as shown. &nbsp;Wrap each petal with a 2" x 1" outline strip.</p>'},
        {img: "assets/images/artwork/clay/striped6tear/striped6tear6.jpg",
         desc: '<p>Starting at the lighter-colored (1" wide) end of the 1.5" x 1" Skinner blend, roll the blend strip into a jelly roll to use as the center of the flower. &nbsp;Arrange the petals around the center so that the rounded ends of the petals touch the center piece. &nbsp;The stripes in the petals should point toward the center.</p>'},
        {img:"assets/images/artwork/clay/striped6tear/striped6tear7.jpg",
         desc: '<p>Place your thumb and pointer finger on the sides of each petal and gently press it toward the center to make sure it adheres to the center and any gaps are closed. &nbsp;Press each petal evenly so the finished flower is balanced.</p>'}
      ]
    },
    { id: 4000016, 
      title: 'Swirl Butterfly Cane', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/butterfly/butterfly8.jpg',
      desc: '<p>These instructions are for the class auction project.</p><p>Materials:</p><p>4 - 5.5" x 1.5" matching Skinner blend strips (#4)<br />1 - 3/4" x 1.5" strip for the antennae (in body color)</p>',
      date: '19 Jan 2013',
      content: [
        {img:"assets/images/artwork/clay/butterfly/butterfly1.jpg",
         desc: '<p>Begin with four matching 5.5" x 1.5" Skinner blends. &nbsp;One end of the blend will be the color of the inner wing and the other will be the color of the outer wing/body. &nbsp;The 3/4" x 1.5" antennae strip is the same color as the outer wing/body. &nbsp;Use this fact to determine which end of the blend strip is the inner wing.</p>'},
        {img:"assets/images/artwork/clay/butterfly/butterfly2.jpg",
         desc: '<p>Starting at the inner-wing-colored end of the blend strip, roll each strip into a jelly roll shape, stopping 1/2" from the other end of the strip to leave a 1/2" extension.</p>'},
        {img:"assets/images/artwork/clay/butterfly/butterfly3.jpg" ,
         desc: '<p>Separate the rolls into two pairs, placing each pair "back-to-back" so that the outsides of the their extensions face each other (as shown). </p>'},
        {img:"assets/images/artwork/clay/butterfly/butterfly4.jpg",
         desc: '<p>Join each pair of rolls by lining up the edges of their extensions and gently pressing them together.</p>'},
        {img:"assets/images/artwork/clay/butterfly/butterfly5.jpg",
         desc: '<p>Then press these joined extensions back toward the rolls as shown. &nbsp;(These ends will become the body of the butterfly.) &nbsp;The joined rolls will form a "B" shape with one side flatter than the other.</p>'},
        {img: "assets/images/artwork/clay/butterfly/butterfly6.jpg",
         desc: '<p>Press the two pairs of rolls together on their "flat" sides. &nbsp;Shape one pair of rolls into upper wings and the other pair into lower wings, as shown.</p>'},
        {img:"assets/images/artwork/clay/butterfly/butterfly7.jpg",
         desc: '<p>Fold the remaining 3/4" x 1.5" antennae strip in half lengthwise to form a "V" shape.</p>'},
        {img: "assets/images/artwork/clay/butterfly/butterfly8.jpg",
         desc: '<p>Place the "V" strip into the gap between the upper wings of the butterfly to form its antennae.</p>'}
      ]
    },
    {id: 4000017, 
      title: 'Teardrop Leaf Cane', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/teardropleaf/teardropleaf11.jpg',
      desc: '<p>These instructions are for the auction project.</p><p>Materials (Clay):</p><p>1 - 8" x 2" Skinner blend strip (#7)<br />3 - 1.5" x 2" flat vein strips (#6)<br />1 - 5" x 2" flat outline strip (#6)</p>',
      date: '7 Jan 2013',
      content: [
        {img:"assets/images/artwork/clay/teardropleaf/teardropleaf1.jpg",
         desc: '<p>Starting at the lighter-colored narrow (2" wide) end, roll the 8" x 2" Skinner blend into a jelly roll.</p>'},
        {img:"assets/images/artwork/clay/teardropleaf/teardropleaf2.jpg",
         desc: '<hr>'},
        {img:"assets/images/artwork/clay/teardropleaf/teardropleaf3.jpg" ,
         desc: '<p>Set the jelly roll on its round end so you can see the spiral pattern on top. &nbsp;Mark two parallel lines across the top, each a third of the way in from the edge.</p><hr>'},
        {img:"assets/images/artwork/clay/teardropleaf/teardropleaf4.jpg",
         desc: '<p>Slice straight down through the marks, keeping the cut perpendicular to the top of the roll and desk.</p><hr>'},
        {img:"assets/images/artwork/clay/teardropleaf/teardropleaf5.jpg",
         desc: '<p>Place a 1.5" x 2" flat vein strip on the cut side of each of the outer slices.</p><hr>'},
        {img: "assets/images/artwork/clay/teardropleaf/teardropleaf6.jpg",
         desc: '<p>With the vein strips still in place, press the slices back in place against the center slice.</p><hr>'},
        {img:"assets/images/artwork/clay/teardropleaf/teardropleaf7.jpg",
         desc: '<p>Now make a slice mark on the top of the roll that is at a 45 degree angle from the first two slice marks you made. &nbsp;Slice straight down through the mark to the bottom of the roll, keeping your cut perpendicular to the top of the roll and the desk.</p><hr>'},
        {img: "assets/images/artwork/clay/teardropleaf/teardropleaf8.jpg",
         desc: '<p>Place the third 1.5" x 2" flat vein strip on the flat side of one of the halves you just cut.</p>'},
        {img:"assets/images/artwork/clay/teardropleaf/teardropleaf9.jpg",
         desc: "<p>Place the other half on top of the vein strip but spin the half around so that existing vein lines in the two halves form a \"V\". &nbsp;(See picture.) &nbsp;Press the two halves together until they adhere.</p><hr>"},
        {img:"assets/images/artwork/clay/teardropleaf/teardropleaf10.jpg",
         desc: "<p>Wrap the 5\" x 2\" outline strip around the outside of the roll.</p><hr>"},
        {img:"assets/images/artwork/clay/teardropleaf/teardropleaf11.jpg",
         desc: '<p>Press in on the sides of the roll gently to close any gaps. &nbsp;Shape the roll into a teardrop shape to make the leaf, having the pointed end of the teardrop lined up along the top of the center vein and the "V" from the side veins opening toward the point.</p>'}
      ]
    },
    { id: 4000018, 
      title: 'Vases: Red-to-Violet', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/vases/vases1.jpg',
      desc: "<p>My son's fifth grade class had to provide a project for the school's annual auction. &nbsp;As room parent, I suggested that we make a polymer-clay covered vase, which was an idea I'd done with my daughter's fifth grade class&nbsp;at a different school five years earlier. &nbsp;That earlier vase had sold very well and the kids enjoyed making it -- though it was a lot of work. &nbsp;Fortunately, I'd saved a lot of the cane templates I'd made up from that first experience and was able to reuse them as a starting point for my son's class. &nbsp;For my daughter's school, each class was responsible for its own project but at my son's school, the project is made at a grade level. &nbsp;There were two classes in fifth grade, so working together with the other class' room parent, we made two vases. &nbsp;Here are the results:</p>",
      date: '15 Oct 2012',
      content: [
        {img:"assets/images/artwork/clay/vases/vases1.jpg",
         desc: '<p>These vases were made using slices of canes that the kids made, working mostly in pairs. &nbsp;(Some of the simpler canes were made by individual students.) &nbsp;We used about 7 cane patterns, each in three or four color schemes, to end up with about 25 different canes. &nbsp;I provided a finished sample cane and step-by-step instructions for each cane pattern. &nbsp;Kids with the same cane pattern were assigned to an adult, who guided the kids through the creation of their canes. &nbsp;</p><p>We parents did a lot of set up work (softening the clay, dividing and either rolling it into balls that the kids would roll out into logs or running it through the pasta machine to make flats, and putting the &nbsp;materials needed for a cane into a single ziplock bag) so that we only needed to take about 45 minutes of class time working with the kids.</p>'},
        {img:"assets/images/artwork/clay/vases/vases2.jpg",
         desc: '<p>Certainly we could have had the kids do more of this work (which is how I did it with my daughter\'s class) but you have to be prepared for it to take much longer and require more parent supervision.</p><p>After the kids finished making the canes, I took them home and reduced them to about 1/2" diameter. &nbsp;The room moms and a few other parents got together to cover the vases with slices of the canes. &nbsp;(Again, you could have the kids participate in this step if you have enough time and supervision.) &nbsp;We cut the reduced canes in half so that each vase had its own supply of all 25 canes, then one parent per vase sliced canes into 1/16 - 1/8" disks while the other parent covered the vases starting at the bottom (vase turned upside down) and working toward the top. &nbsp;It took about 8 hours to finish each vase, which was approximately 13" tall. &nbsp;I baked, sanded and glazed the vases while another parent built beautiful gloss black stands for them. &nbsp;We special-ordered plaques that were engraved with the year, class, auction name and school to mount on the front of the stands. &nbsp;Voila!</p>'}
      ]
    },
    { id: 4000019, 
      title: 'Pillar Candle Holder', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/pillarHolder/pillarHolder1.jpg',
      desc: "<p></p>",
      date: '9 Jun 2016',
      content: [
        {img:"assets/images/artwork/clay/pillarHolder/pillarHolder1.jpg",
         desc: '<p></p>'},
        {img:"assets/images/artwork/clay/pillarHolder/pillarHolder2.jpg",
         desc: '<p></p>'}
      ]
    },
    { id: 4000020, 
      title: 'Dessert Bowl', 
      category: 'Polymer Clay', 
      summary: '',
      coverImg: 'assets/images/artwork/clay/dessertBowl/dessertBowl1.jpg',
      desc: "<p></p>",
      date: '9 Jun 2016',
      content: [
        {img:"assets/images/artwork/clay/dessertBowl/dessertBowl1b.jpg",
         desc: '<p>I added small cane slices (~3/8" diameter) to this is simple dessert bowl to make it look like the flowers are growing up the sides of the bowl.</p>'},
        {img:"assets/images/artwork/clay/dessertBowl/dessertBowl2.jpg",
         desc: '<p>We decided to use it as a candle holder rather than for serving food.</p>'},
         {img:"assets/images/artwork/clay/dessertBowl/dessertBowl3.jpg",
         desc: '<p></p>'}
      ]
    }
  ],
  [
    { id: 5000000, 
      title: 'Gingerbread House', 
      category: 'Miscellaneous', 
      summary: 'Submission for Wilton Competition', 
      coverImg: 'assets/images/artwork/misc/gingerbreadhouse.jpg',
      desc: '',
      date: '2011',
      content: [
        {img:'assets/images/artwork/misc/gingerbreadhouse.jpg',
         desc: '<p>I made this gingerbread house for a Wilton competition several years ago.</p>       <p>The structure is made of gingerbread that is connected with brown royal icing.  Before the gingerbread panels were connected, the window openings were carved out and filled with yellow royal icing and then covered in hot melted sugar that hardened as it cooled to form a glassy look.</p>  <p>The roof is made from wafer cookies.  The porch posts are candy canes and the railing is made from royal icing that was piped to the shape on wax paper and allowed to dry. The garland is green licorice strands and the bows are piped from red royal icing.  The porch base and front steps are made from graham crackers.  The lights along the gutter line are candy pieces and the front fascia above the second story balcony is covered in smarties candy pieces.  The evergreen trees are made from sugar cookies cut in variously-size star shapes and stacked from largest to smallest, connected with royal icing.  The shrubs are gum drops overpiped with green royal icing using a star tip.  The window trim and wreaths were also piped using royal icing.</p> <p>Santa, the snowman and the lamppost were made from fondant.  The bricks of the chimney surrounding Santa are made from Chicklets gum pieces.  Snowman\'s scarf is a piece of fruit rollup.</p>  <p>The house is approximately 12\" x 12\" x 12\".</p>'}
      ],
    },
    { id: 5000001, 
      title: 'Hand-stamped Notebook Cover', 
      category: 'Miscellaneous', 
      summary: 'A simple gift', 
      coverImg: 'assets/images/artwork/misc/notebook.jpg',
      desc: '<p>I livened up a plain cardboard notebook by adding a cover made from a collage of stamped images (from Stampin\ Up.)</p>',
      date: '2011',
      content: [
        {img:'assets/images/artwork/misc/notebook.jpg',
         desc: '<p></p>'}
      ],
    },
    { id: 5000002, 
      title: 'Stamped, Painted Glass Angel Ornament', 
      category: 'Miscellaneous', 
      summary: 'A Christmas gift for a teacher', 
      coverImg: 'assets/images/artwork/misc/ornaments.jpg',
      desc: '<p>I decorated this glass Christmas ornament for a teacher\'s gift.  It is stamped with four tiny angels in permanent ink.  I colored the angels using paint pens then wrote \'Hark! the herald angels sing, "Glory to the newborn King"!\' </p>',
      date: '6 Nov 2012',
      content: [
        {img:'assets/images/artwork/misc/ornaments.jpg',
         desc: '<p></p>'}
      ],
    },
    { id: 5000003, 
      title: 'Fruit Notecards', 
      category: 'Miscellaneous', 
      summary: 'Stamped and embossed notecards in a holder', 
      coverImg: 'assets/images/artwork/misc/fruitcards.jpg',
      desc: '<p></p>',
      date: '6 Nov 2012',
      content: [
        {img:'assets/images/artwork/misc/fruitcards.jpg',
         desc: '<p>A set of six notecards embossed on the outside with a checkerboard design and fruit border.  Inside the cutaway window is a matching fruit stamped and colored with watercolor pencils.  </p>'},
         {img:'assets/images/artwork/misc/fruitcards2.jpg',
         desc: '<p></p>'},
         {img:'assets/images/artwork/misc/fruitcards1.jpg',
         desc: '<p>The card holder is made from cardstock.</p>'}
      ],
    }
  ]
];
